### ISSUE TITLE
Example link gives 404

### ISSUE THREAD

**Issue by joacim-boive** [elfet/svg-embed#1]
http://elfet.github.io/svg-embed/example/

**Comment by antonmedv** [comment]
Thanks! Fixed.

**Comment by spenno** [comment]
It's broken again :)

**Comment by antonmedv** [comment]
Yeah, I've migrated from github pages and forgot to move this as well. Will fix it.

**Comment by antonmedv** [comment]
http://antonmedv.github.io/svg-embed/example/
